### ISSUE TITLE
원과 원의 중심의 가장 가까운 교점은 원의 중심인가

### ISSUE THREAD

**Issue by 20chan** [Big-BlueBerry/GCS.WPF#8]
Geometry 클래스의 `GetNearest` 함수 구현 문제임.

구 GCS의 코드를 보면 다음과 같은 코드가 있어.
```csharp
private static Vector2 getNearest(Circle circle, Vector2 point)
{
    if (circle.Center == point) { return circle.Center; }
    ...
```
일반적으로 원과 점의 교점은 원 위에 있어야 한다고 생각함.
`GetNearestDistance`도 이제 내부적으로 `GetNearest` 를 사용하는데 원의 중심을 리턴하면 원하는데로 작동하지 않을거라고 생각함.

이전 GCS에서 원의 중심을 리턴함으로써 해결할 수 있는 문제나 이점같은게 있었음?

**Comment by yenapple** [comment]
ㄴㄴ 없었음. 단지 임시방편으로 저렇게 해 놓은 거였음. 그런데 중심에서는 어느 점이나 이르는 거리가 똑같기에 어떤 점으로 할지 애매하기도 하고

**Comment by yenapple** [comment]
GetNearestDistance 에서는 Center 입력이 들어오면 그냥 반지름을 리턴해 주면 됨. 그렇게만 하면 딱히 제대로 안 작동하지도 않을 듯

**Comment by 20chan** [comment]
그렇지... 그러면 GetNearest 에서는 Another 리턴하는건 어떰?

**Comment by yenapple** [comment]
문제 없음, 원 위에 있는 게 일관적이라면 Another 로 리턴해도 ㄱㅊ

**Comment by 20chan** [comment]
ㅇㅋ 땡큐
